import type {JSX} from 'preact';
import type {GistFile} from '../apis/gist-api';
import type {AuthorizedAuthStore} from '../hooks/use-auth-store';
import {useGistsStore} from '../hooks/use-gists-store';
import {CollectionControl} from './collection-control';
import {CollectionItem} from './collection-item';
import {Grid} from './grid';

export interface CollectionListProps {
  readonly authStore: AuthorizedAuthStore;
}

const mainFile: GistFile = {
  filename: `.bookmark.wtf.md`,
  text: `# This gist is automatically generated by https://bookmark.wtf`,
};

export function CollectionList({
  authStore,
}: CollectionListProps): JSX.Element | null {
  const gistsStore = useGistsStore(authStore, mainFile);

  if (gistsStore.state === `failed`) {
    throw gistsStore.reason;
  }

  return gistsStore.state !== `loading` ? (
    <Grid>
      <CollectionControl gistsStore={gistsStore} />

      {gistsStore.gists.map((gist) => (
        <CollectionItem
          key={gist.gistName}
          gistsStore={gistsStore}
          gist={gist}
        />
      ))}
    </Grid>
  ) : null;
}
