name: CI
on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version

      - uses: bahmutov/npm-install@v1
      - run: npm run ci

      - run: >-
          npm run build:dev && npx start-server-and-test 'npm start' 3000 'npm
          run e2e-test'
        env:
          DEBUG: pw:api
          CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }}
          E2E_TEST_ORIGIN: http://localhost:3000
          E2E_TEST_LOGIN: ${{ secrets.ITEST_LOGIN }}
          E2E_TEST_PASSWORD: ${{ secrets.ITEST_PASSWORD }}
          E2E_TEST_SECRET: ${{ secrets.ITEST_SECRET }}

      - run: npm run deploy -- --require-approval never
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          CLIENT_ID: ${{ secrets.PROD_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.PROD_CLIENT_SECRET }}
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: npm run e2e-test
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          DEBUG: pw:api
          E2E_TEST_ORIGIN: https://bookmark.wtf
          E2E_TEST_LOGIN: ${{ secrets.ITEST_LOGIN }}
          E2E_TEST_PASSWORD: ${{ secrets.ITEST_PASSWORD }}
          E2E_TEST_SECRET: ${{ secrets.ITEST_SECRET }}
