name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        run: echo NODE_VERSION=$(cat .node-version) >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Run CI checks
        env:
          PROD_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: npm run ci

      - name: Deploy to AWS
        if: github.ref == 'refs/heads/main'
        env:
          AWS_REGION: 'eu-central-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        run: npm run deploy -- --require-approval never

      - name: Run integration tests
        if: github.ref == 'refs/heads/main'
        env:
          ITEST_LOGIN: ${{ secrets.ITEST_LOGIN }}
          ITEST_PASSWORD: ${{ secrets.ITEST_PASSWORD }}
          ITEST_SECRET: ${{ secrets.ITEST_SECRET }}
        run: npm run itest
