name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        run: echo NODE_VERSION=$(cat .node-version) >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Run CI checks
        run: npm run ci

      - name: Run integration tests on localhost
        env:
          DEBUG: 'pw:api'
          CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }}
          ITEST_BASE_URL: 'http://localhost:3000'
          ITEST_LOGIN: ${{ secrets.ITEST_LOGIN }}
          ITEST_PASSWORD: ${{ secrets.ITEST_PASSWORD }}
          ITEST_SECRET: ${{ secrets.ITEST_SECRET }}
        run: npm run itest:dev

      - name: Deploy to AWS
        if: github.ref == 'refs/heads/main'
        env:
          CLIENT_ID: ${{ secrets.PROD_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.PROD_CLIENT_SECRET }}
          AWS_REGION: 'eu-central-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        run: npm run deploy -- --require-approval never

      - name: Run integration tests on bookmark.wtf
        if: github.ref == 'refs/heads/main'
        env:
          ITEST_BASE_URL: 'https://bookmark.wtf'
          ITEST_LOGIN: ${{ secrets.ITEST_LOGIN }}
          ITEST_PASSWORD: ${{ secrets.ITEST_PASSWORD }}
          ITEST_SECRET: ${{ secrets.ITEST_SECRET }}
        run: npm run itest:prod
