jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
    - uses: bahmutov/npm-install@v1
    - run: npm run ci
    - run: npx playwright install --with-deps
    - env:
        CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }}
        GITHUB_LOGIN: ${{ secrets.ITEST_LOGIN }}
        GITHUB_PASSWORD: ${{ secrets.ITEST_PASSWORD }}
        GITHUB_SECRET: ${{ secrets.ITEST_SECRET }}
      run: npm run build:dev && npm run test:e2e:localhost
    - env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_REGION: eu-central-1
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CLIENT_ID: ${{ secrets.PROD_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.PROD_CLIENT_SECRET }}
      if: ${{ github.ref == 'refs/heads/main' }}
      run: npm run deploy -- --require-approval never
    - env:
        GITHUB_LOGIN: ${{ secrets.ITEST_LOGIN }}
        GITHUB_PASSWORD: ${{ secrets.ITEST_PASSWORD }}
        GITHUB_SECRET: ${{ secrets.ITEST_SECRET }}
      if: ${{ github.ref == 'refs/heads/main' }}
      run: npm run test:e2e
name: CI
on:
  pull_request: {}
  push: {}
