name: CI
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install dependencies
        run: yarn install

      - name: Run CI checks
        env:
          CI: true
          PROD_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: yarn ci

      - name: Deploy to AWS
        if: github.ref == 'refs/heads/main'
        env:
          AWS_REGION: 'eu-central-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
          HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}
        run: yarn deploy --require-approval never
